const APP_TITLE = "Seajeite";
const int NOTIFY_INTERVAL = 1;
const int NOTIFY_TIMES = 6;
const NOTIFY_TEXT = "Arruma essa postura, seu arrombado!";
const DESCRIPTION_NOTIFY_CHN = "Lembrete de correção postural";
const NAME_NOTIFY_CHN = "Se ajeite";
const DESCRIPTION_START = "Iniciar";
const DESCRIPTION_STOP = "Parar";
const DESCRIPTION_ACTIVITY_TIME = "TEMPO DE ATIVIDADE";